### ISSUE TITLE
email_trigger_KEYS Question

### ISSUE THREAD

**Issue by julianlmedina** [tdavis-ourfuture/SalsaPHP#2]
Hi:

If I try forking Supporter.php, will I be able to add email_trigger_KEYS as a parameter for a new supporter?

Thanks!

**Comment by asithade** [comment]
Hi Julian,

Here's how that would work. 

``` php
$supporter = SalsaPHP\Supporter::addSupporter($email, $firstname, $lastname, $zipcode, array('email_trigger_KEYS' => $email_trigs));
```

**Comment by julianlmedina** [comment]
Thanks!! Will fork and give it a try hopefully tonight.
